// <auto-generated />
namespace Magic_Moonlight_Cinema.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class imageURLcinema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(imageURLcinema));
        
        string IMigrationMetadata.Id
        {
            get { return "202309121237176_imageURL-cinema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
