// <auto-generated />
namespace Magic_Moonlight_Cinema.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class moviecinema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(moviecinema));
        
        string IMigrationMetadata.Id
        {
            get { return "202309121234159_movie-cinema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
