// <auto-generated />
namespace Magic_Moonlight_Cinema.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class maybeLast : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(maybeLast));
        
        string IMigrationMetadata.Id
        {
            get { return "202309132158181_maybeLast"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
